# Generated by Django 4.0.2 on 2022-02-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(blank=True, null=True, upload_to='Home/backgrounds')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Home/logos')),
                ('name', models.CharField(default='John Doe', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
