# Generated by Django 4.0.2 on 2022-02-23 23:46

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_me')),
                ('title', models.CharField(max_length=200)),
                ('description', django_quill.fields.QuillField()),
            ],
        ),
    ]
