# Generated by Django 4.0.2 on 2022-02-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
