# Generated by Django 4.0.2 on 2022-02-24 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_counts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counts',
            new_name='Count',
        ),
    ]
