# Generated by Django 4.0.2 on 2022-02-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0006_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials')),
                ('name', models.CharField(max_length=200)),
                ('positions', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
