# Generated by Django 4.0.2 on 2022-02-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0007_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='positions',
            new_name='position',
        ),
    ]
