# Generated by Django 4.0.2 on 2022-02-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0008_rename_positions_testimonial_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='show_counts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='show_interests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='show_skills',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='show_testimonials',
            field=models.BooleanField(default=True),
        ),
    ]
