# Generated by Django 4.0.2 on 2022-02-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0009_aboutme_show_counts_aboutme_show_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='interests_title',
            field=models.CharField(default='Tnterests', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='skills_title',
            field=models.CharField(default='Skills', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='testimonials_title',
            field=models.CharField(default='Testimonials', max_length=200),
        ),
    ]
