# Generated by Django 4.0.2 on 2022-02-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='src/logos')),
                ('isotipo', models.ImageField(blank=True, null=True, upload_to='src/isotipos')),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('color_light', models.CharField(blank=True, max_length=100, null=True)),
                ('home_name', models.CharField(default='Home', max_length=100)),
                ('about_name', models.CharField(default='About', max_length=100)),
                ('about_title', models.CharField(default='Learn more about me', max_length=100)),
                ('show_about', models.BooleanField(default=True)),
                ('resume_name', models.CharField(default='Resume', max_length=100)),
                ('resume_title', models.CharField(default='Check my resume', max_length=100)),
                ('show_resume', models.BooleanField(default=True)),
                ('services_name', models.CharField(default='Services', max_length=100)),
                ('services_title', models.CharField(default='My services', max_length=100)),
                ('show_services', models.BooleanField(default=True)),
                ('portfoio_name', models.CharField(default='Portfoio', max_length=100)),
                ('portfoio_title', models.CharField(default='My works', max_length=100)),
                ('show_portfoio', models.BooleanField(default=True)),
                ('contact_name', models.CharField(default='Contact', max_length=100)),
                ('contact_title', models.CharField(default='Contact me', max_length=100)),
                ('show_contact', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
