# Generated by Django 4.0.2 on 2022-02-17 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='Source',
        ),
    ]
