# Generated by Django 4.0.2 on 2022-02-19 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_source_contact_address_lable_source_contact_btn_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='logo',
        ),
    ]
