# Generated by Django 4.0.2 on 2022-02-19 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_remove_source_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('source', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='src.source')),
            ],
        ),
    ]
