# Generated by Django 4.0.2 on 2022-03-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_socialnetwork_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='source',
        ),
    ]
