# Generated by Django 4.0.2 on 2022-03-07 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_remove_socialnetwork_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='source',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='src.source'),
        ),
    ]
