# Generated by Django 4.0.2 on 2022-03-07 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_socialnetwork_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='src.source'),
        ),
    ]
