# Generated by Django 4.0.2 on 2022-03-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_alter_socialnetwork_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='source',
        ),
        migrations.AddField(
            model_name='source',
            name='services_test',
            field=models.BooleanField(default=True),
        ),
    ]
