# Generated by Django 4.0.2 on 2022-03-07 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_remove_socialnetwork_source_source_services_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='services_test',
        ),
        migrations.AddField(
            model_name='source',
            name='services_col_lg',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='source',
            name='services_col_md',
            field=models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
    ]
