# Generated by Django 4.0.2 on 2022-03-07 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_remove_source_services_test_source_services_col_lg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='source',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='src.source'),
        ),
    ]
