# Generated by Django 5.0.6 on 2024-06-12 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_socialnetwork_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='src.source'),
        ),
    ]
