# Generated by Django 4.0.2 on 2022-03-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='position',
        ),
        migrations.AddField(
            model_name='section',
            name='position',
            field=models.CharField(choices=[('left', '1'), ('right', '2')], default='left', max_length=10),
        ),
    ]
