# Generated by Django 4.0.2 on 2022-03-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_remove_item_position_section_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='position',
            field=models.CharField(choices=[('order-first', 'left'), ('order-last', 'right')], default='left', max_length=50),
        ),
    ]
