# Generated by Django 4.0.2 on 2022-03-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0003_alter_section_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='position',
            field=models.CharField(choices=[('left', 'order-first'), ('right', 'order-last')], default='left', max_length=50),
        ),
    ]
