# Generated by Django 4.0.2 on 2022-03-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0004_alter_section_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='position',
        ),
    ]
