# Generated by Django 5.0.6 on 2024-06-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0005_remove_section_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-start']},
        ),
    ]
